### ISSUE TITLE
How to load images from URL?

### ISSUE THREAD

**Issue by MrRochito** [michaelbabiy/RMParallax#11]
Hi, is possible load images from an url?

greetings

**Comment by michaelbabiy** [comment]
You can load images from the internet, yes. You'll need to write a client to download images to the device and then set them as needed. 

I am not sure this is ideal since RMParallax was written with a specific purpose in mind... Besides, network calls can take a while depending on a connection. If thats the case, having users wait for images to load on the first screen of your app is a very bad user experience.

If you absolutely need to download images from the internet, (lets assume you are building the best wallpapers app there is) get 3 - 4 images depending on the image size and keep a buffer of 1-2 images as the user swipes.

This is something you will have to test and see.

Hope this helps.
